version: "3"

services:

  php74:
    image: php:7.4
    volumes:
      - ./src:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: php -a

  php80:
    image: php:8.0-rc
    volumes:
      - ./src:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: php -a
