version: "3"

services:

  php74:
    image: php:7.4
    volumes:
      - ./examples:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: bash

  php80:
    image: php:8.0
    volumes:
      - ./examples:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: bash
